# Matrizes

<a href="https://githubtocolab.com/cn-ufpe/cn-ufpe.github.io/blob/master/material/08_matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab"/></a>

## Inicialização de matrizes

In [ ]:
import numpy as np

Inicialização com todos os elementos iguais a zero

In [ ]:
A = np.zeros((2, 3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]]


Todos os elementos iguais a 1

In [ ]:
B = np.ones((4, 5))
print(B)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Matriz identidade

In [ ]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Matriz diagonal

In [ ]:
np.diag([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diag([1, 1, 1], -1)

array([[0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

Matriz aleatória

In [ ]:
# np.random.seed(1)
R = np.random.rand(5,5)
R

array([[0.89460666, 0.08504421, 0.03905478, 0.16983042, 0.8781425 ],
       [0.09834683, 0.42110763, 0.95788953, 0.53316528, 0.69187711],
       [0.31551563, 0.68650093, 0.83462567, 0.01828828, 0.75014431],
       [0.98886109, 0.74816565, 0.28044399, 0.78927933, 0.10322601],
       [0.44789353, 0.9085955 , 0.29361415, 0.28777534, 0.13002857]])

A partir de uma lista

In [ ]:
A = [[1, 2, 3, 2], [5, 2, 1, 3], [9, 3, 4, 4]]
A = np.array(A)
print(A)

[[1 2 3 2]
 [5 2 1 3]
 [9 3 4 4]]


### Acessar elementos de uma matriz

In [ ]:
A[1, 0]

5

Linhas e colunas com o operador "dois pontos"

In [ ]:
linha0 = A[[0],:]
print(linha0)
print(linha0.shape)

[[1 2 3 2]]
(1, 4)


In [ ]:
A[0: 2,:]

array([[1, 2, 3, 2],
       [5, 2, 1, 3]])

In [ ]:
A[:]

array([[1, 2, 3, 2],
       [5, 2, 1, 3],
       [9, 3, 4, 4]])

In [ ]:
A[:, [2]]

array([[3],
       [1],
       [4]])

In [ ]:
A[:, 0:3]

array([[1, 2, 3],
       [5, 2, 1],
       [9, 3, 4]])

In [ ]:
A[:, [0,3]]

array([[1, 2],
       [5, 3],
       [9, 4]])

### Multiplicação de matrizes

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [3, 2, 2]])
b = np.array([[1], [2], [1]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 2]])

In [ ]:
b

array([[1],
       [2],
       [1]])

In [ ]:
A @ b

array([[ 8],
       [20],
       [ 9]])

In [ ]:
print(b.shape)

(3, 1)


In [ ]:
b @ b

ValueError: ignored

Transposta

In [ ]:
b.T @ b

array([[6]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 2]])

In [ ]:
A.T

array([[1, 4, 3],
       [2, 5, 2],
       [3, 6, 2]])

In [ ]:
vetor = np.array([1, 2, 3])

In [ ]:
vetor

array([1, 2, 3])

In [ ]:
vetor.T

array([1, 2, 3])

In [ ]:
vetor.shape

(3,)

In [ ]:
vetor.shape = (3, 1)

In [ ]:
vetor.T

array([[1, 2, 3]])

In [ ]:
vetor

array([[1],
       [2],
       [3]])

In [ ]:
help(np.zeros)

Help on built-in function zeros in module numpy:

zeros(...)
    zeros(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or tuple of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this arg

In [ ]:
def minha_funcao(x):
  '''
  descrição da minha função
  '''
  return x

In [ ]:
minha_funcao(3)

3

In [ ]:
help(minha_funcao)

Help on function minha_funcao in module __main__:

minha_funcao(x)
    descrição da minha função



In [ ]:
np.zeros?

In [ ]:
minha_funcao?