In [1]:
import numpy as np

### Calculando a Eliminação Gaussiana com a função Solve

In [2]:
# Criando array A
A = np.array([[3, 2, 7], [-6, 5, 1], [3, 11, -1]])

In [3]:
# Criando array b
b = np.array([[8], [-10], [-9]])

In [4]:
# Calculando a eliminacao gaussiana com a funcao solve
np.linalg.solve(A, b)

array([[ 1.],
       [-1.],
       [ 1.]])

### Calculando a Eliminação Gaussiana passo a passo

In [5]:
# Imprimindo a matriz A
A

array([[ 3,  2,  7],
       [-6,  5,  1],
       [ 3, 11, -1]])

In [6]:
# Imprimindo a matriz b
b

array([[  8],
       [-10],
       [ -9]])

In [7]:
# calculando a lin 1 col 0 a 2 de A e lin 1 de b
A[1, 0] = A[1, 0] + 2 * A[0, 0]
A[1, 1] = A[1, 1] + 2 * A[0, 1]
A[1, 2] = A[1, 2] + 2 * A[0, 2]
b[1] = b[1] + 2 * b[0]

In [8]:
# calculando a lin 2 col 0 a 2 de A e lin 2 de b
A[2, 0] = A[2, 0] - 1 * A[0, 0]
A[2, 1] = A[2, 1] - 1 * A[0, 1]
A[2, 2] = A[2, 2] - 1 * A[0, 2]
b[2] = b[2] - 1 * b[0]

In [9]:
# calculando a lin 2 col 2 de A e lin 2 de b
A[2, 0] = A[2, 0] - 1 * A[1, 0]
A[2, 1] = A[2, 1] - 1 * A[1, 1]
A[2, 2] = A[2, 2] - 1 * A[1, 2]
b[2] = b[2] - 1 * b[1]

In [10]:
# Imprimindo a matriz A
A

array([[  3,   2,   7],
       [  0,   9,  15],
       [  0,   0, -23]])

In [11]:
# Imprimindo a matriz b
b

array([[  8],
       [  6],
       [-23]])

In [12]:
# Calculo da variável x2
x2 = A[2, 2] / b[2]
x2

array([1.])

In [13]:
# Calculo da variável x1
x1 = (b[1] - A[1, 2] * x2) / A[1, 1]
x1

array([-1.])

In [14]:
# Calculo da variável x0
x0 = (b[0] - A[0, 1] * x1 - A[0, 2] * x2) / A[0, 0]
x0

array([1.])